### ISSUE TITLE
Footer title goes beyond width on small screens

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#10]
The footer branding goes beyond the screen width, and causes horizontal scrolling.

iPhone 5S:
![img_19dfedb1c47c-1](https://user-images.githubusercontent.com/560463/38315054-894b6dae-381f-11e8-97b5-5bd48203be34.jpeg)

**Comment by BenDarby** [comment]
fixed by reducing logo size on mobile
