### ISSUE TITLE
Reduce the size of hero padding

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Pattern-Library#100]
Copied over from IATI-Standard-Website: 
@k8hughes:

>  UNDP have requested that we reduce the size of the hero images by 20%. I'm worried that that might be too much. can you have a go at this and deploy to staging so we can show to them and discuss?

**Comment by k8hughes** [comment]
I have spoken to Annalise and she'd like to go ahead with the 20% reduction.  
It was hard to tell from the screen shots what the impact was going to be, you need to see it on the screen to really get it so I didn't show her the presentation.

**Comment by k8hughes** [comment]
To me it doesn't look like much difference, can we try 40% and see how that looks?

**Comment by Ocre42** [comment]
Updating the issue to properly address what needs to be reduced
