### ISSUE TITLE
Add youtube icon linked to the IATI youtube account into the footer 

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Pattern-Library#101]
This is a link to our youtube account: https://www.youtube.com/channel/UCAVH1gcgJXElsj8ENC-bDQQ

Please can this be added to the footer.

Priority todo asap.

(Copied from https://github.com/IATI/IATI-Standard-Website/issues/324)

**Comment by samuele-mattiuzzo** [comment]
- add `--youtube` item to `assets/css/modules/_social.scss`
- update `includes/scaffold/footer.html` to include the new icon
- find the YouTube icon (speak with @benjamincoleman about the SVG file)
