### ISSUE TITLE
T9.0 The Standard

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#118]
Sketch - https://marvelapp.com/4cfjg52/screen/60336730

This template appears at the top of the IA for this section:

https://cloudup.com/ixe6qYM4P0V

It has an introduction, then three blocks to introduce various areas: 

- The Standard
- Upgrades
- Other links

---

Design: http://iati.surge.sh/page-templates/09-the-standard

**Comment by benjamincoleman** [comment]
@BenDarby Changes: 

- [ ] links and para look very similar here - could use something to distinguish them further.

**Comment by BenDarby** [comment]
@benjamincoleman links have a thick light blue border on them though?

**Comment by benjamincoleman** [comment]
@BenDarby update to The Standard page - https://marvelapp.com/4cfjg52/screen/60336730

There’s now 4 boxes instead of 3
