### ISSUE TITLE
T11 Community

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#126]
Template for the community page

Sketch: https://marvelapp.com/4cfjg52/screen/61443824

Design: http://iati.surge.sh/page-templates/10-community

**Comment by BenDarby** [comment]
@benjamincoleman  I've used modules from the homepage as they suited the content in this template well, also I moved the small bit of text about conduct into the sidebar and gave it the more impactful style we have for this elements. Template here http://iati.surge.sh/page-templates/10-community

**Comment by benjamincoleman** [comment]
@BenDarby can you rename this to "Get involved" please?
