### ISSUE TITLE
T2.9 Standard Guidance

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#128]
Sketch is here: https://marvelapp.com/4cfjg52/screen/62575949

Checkboxes can just be checkboxes in the filter - not custom ones.

**Comment by benjamincoleman** [comment]
Sketch feedback from Petya: 

> Could we change to 'Filter by file type' organisation and activity. It will be difficult to add more logical topics to the guidance pages.

> Like the search. Maybe the 'Search' box can be made a bit bigger as the filtering will only have two options.

**Comment by BenDarby** [comment]
@benjamincoleman  added template to pl http://iati.surge.sh/page-templates/02-9-standard-guidance

**Comment by benjamincoleman** [comment]
@BenDarby can you remove two of the filter options please: 

- budgets
- codelists

Thanks
