### ISSUE TITLE
Update design of sidebar navigation - icons

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#129]
Replace icons to match this design: 

You can find the sketch file for this here - [Reference menu styles.sketch](https://www.dropbox.com/s/vywo0i2mw24bq80/Reference%20menu%20styles.sketch?dl=0) 
 
![Screen Shot 2019-10-09 at 09 45 18](https://user-images.githubusercontent.com/64877/66465964-c5ae7d00-ea79-11e9-9f97-00625a9534d7.png)

**Comment by BenDarby** [comment]
@benjamincoleman it's currently one icon which is then rotated using css, I will need to refactor this element to work with using 2 different icons
