### ISSUE TITLE
T6.1 Guidance page

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#141]
Variant of http://iati.surge.sh/page-templates/06-standard-page. 

Move the central column of content to the left and then have "related guidance" boxes in a right sidebar. Design for those should be similar to the ones here: http://iati.surge.sh/page-templates/02-9-standard-guidance

**Comment by BenDarby** [comment]
PL template here: http://iati.surge.sh/page-templates/06-1-guidance-page

Removed the description for the related guidance card in this instance

**Comment by benjamincoleman** [comment]
@BenDarby can we reduce the font size of the title - its going to look bad if we have anything long in there.

**Comment by BenDarby** [comment]
@benjamincoleman I've reduced the size of the titles a little http://iati.surge.sh/page-templates/06-1-guidance-page

**Comment by benjamincoleman** [comment]
Think we need to have this respond a little

Can we take down the font-size a little more, maybe 1.5/1.6 rem

Also the arrangement at around 814px wide screens could do with looking at: 

![Screen Shot 2019-12-09 at 13 35 10](https://user-images.githubusercontent.com/64877/70439883-ddf64480-1a88-11ea-820b-71bf7be600c8.png)

**Comment by BenDarby** [comment]
@benjamincoleman I've updated to decrease font size more and the date sits above title

**Comment by benjamincoleman** [comment]
Lovely
