### ISSUE TITLE
Menu spacing / switch to mobile menu

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#142]
I want to try and decrease the breakpoint for the main menu switch to mobile. 

Basically, we've had more things added and it's causing the menu to move to the mobile version at around 1200px, which is too large a value IMO. 

So, we want to do the following to delay that switch to smaller dimensions. 

Things we can do: 

1. Make the logo smaller
2. Reduce font size
3. Reduce left/right padding on menu links to squeeze them up a bit

**Comment by BenDarby** [comment]
@benjamincoleman I've reduced the overall width of the menu breakpoint by 200px, let me know what you think http://iati.surge.sh/page-templates/06-1-guidance-page

**Comment by benjamincoleman** [comment]
@BenDarby ok it's smaller, but across the board. What I meant was we'd have a middle space (respond-to-min-max) where the font and spacing is smaller, and that it would remain the same at the larger size.

**Comment by BenDarby** [comment]
@benjamincoleman ah okay, I didn't realise that. I've updated so it goes to normal size etc at larger screens again
