### ISSUE TITLE
Meganav has multiple layout problems on Windows browsers 

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#143]
http://iati.surge.sh/page-templates/08-3-tools-resources

Edge/IE 11/Win 10

#### Meganav has multiple layout problems on Windows browsers 

![Screenshot 2019-12-11 at 15 20 53](https://user-images.githubusercontent.com/560463/70634622-72e47380-1c2a-11ea-8a21-5ed227825315.png)

![Screenshot 2019-12-11 at 15 21 10](https://user-images.githubusercontent.com/560463/70634638-78da5480-1c2a-11ea-8bd8-48c8b1ffe625.png)

![image](https://user-images.githubusercontent.com/560463/70634559-57796880-1c2a-11ea-8dee-b6e349214f98.png)

**Comment by urlsangel** [comment]
@BenDarby 

All fixed apart from this on IE11/Win 10:

![Screenshot 2019-12-11 at 16 06 05](https://user-images.githubusercontent.com/560463/70638130-3ca9f280-1c30-11ea-9cea-4464a949b544.png)

**Comment by BenDarby** [comment]
@urlsangel pushed a fix for this
