### ISSUE TITLE
Remove the publisher count from the homepage

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Pattern-Library#144]
We've had a request from Annaliese to remove the active publisher count from the homepage.  She has said "you can move it somewhere else, but not on the front page where it has such a prominent focus".  This is because we want to move to counting only our active publishers, but its all a bit complicated.

**Comment by benjamincoleman** [comment]
@BenDarby so we want to remove the last box in this array on the homepage: 

<img width="1218" alt="Screen Shot 2020-02-19 at 10 44 17" src="https://user-images.githubusercontent.com/64877/74827260-0316f700-5305-11ea-8e7f-8eb25023e29d.png">

**Comment by BenDarby** [comment]
@benjamincoleman @k8hughes I've updated the pattern library to remove the publisher count. The only markup change is removing the final `stat__body` div as the design amends have been done with CSS. Pattern library link is here http://iati.surge.sh/page-templates/0-home and the change is in a feature branch called `publisher_count`

**Comment by k8hughes** [comment]
A couple of typos - development and activities.
I don't think this matters as long as the dev implementation catches these.

**Comment by k8hughes** [comment]
Yes, the request was certainly deprioritised so I think we can close it
