### ISSUE TITLE
Partners modules misaligned

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#15]
http://iati.surge.sh/page-templates/0-home

iPad Air, landscape:

![img_0012](https://user-images.githubusercontent.com/560463/38413277-1a90bad0-3983-11e8-8000-c2c3663e2e46.PNG)

**Comment by BenDarby** [comment]
Looks like this has been fixed

**Comment by BenDarby** [comment]
should be fixed now
