### ISSUE TITLE
Events page hero out of alignment

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Pattern-Library#16]
![screen shot 2018-04-06 at 14 39 51](https://user-images.githubusercontent.com/23729009/38430078-24c0a882-39b8-11e8-8f3c-6975df71b5e0.png)
Currently finding image in circle is being oddly obscured by the menu header.

**Comment by allthatilk** [comment]
Seems to be when you change your browser font size to large.

**Comment by BenDarby** [comment]
adjusted font sizes to fix this
