### ISSUE TITLE
Homepage on iphone 6/7/8

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Pattern-Library#17]
![homepage1](https://user-images.githubusercontent.com/36768381/39044919-6bd99e8c-4489-11e8-8a74-62fed94ad3b4.JPG)

In image homepage1 you can see how the last 0 comes on a new line.  This looks messy.

![homepage4](https://user-images.githubusercontent.com/36768381/39044956-85095212-4489-11e8-89cc-2a109385ec2e.JPG)

In images homepage4 you can see how all the title text is a mess, single letters on new lines etc.

**Comment by BenDarby** [comment]
dropped font size slightly for mobile
