### ISSUE TITLE
Homepage on IE

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Pattern-Library#20]
A couple of layout bugs on IE.

The photo cut into the logo isn't working.
![homepageie](https://user-images.githubusercontent.com/36768381/39057336-d58734d0-44b0-11e8-865a-3d6324f5c84f.JPG)

The photo's by the partner quotes are aligning incorrectly 
![homepageie2](https://user-images.githubusercontent.com/36768381/39057358-df17782a-44b0-11e8-9ddd-47a753113719.JPG)

**Comment by BenDarby** [comment]
The hero image element is using a css masking to create the image cutout effect, this css function isn't supported in IE11 and below so this is why it's appearing as a normal image. I've put a fix in place to not show the image in this case, so you'll only see the white logo marque instead, I feel like this is the best solution as we still include the strong elements of the branding.
