### ISSUE TITLE
History of IATI cannot take an even number of timeline events

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Pattern-Library#23]
https://iati.surge.sh/page-templates/01-5-history (when using dev tools to delete the last card)

![image](https://user-images.githubusercontent.com/8247168/39058239-26f02bd6-44b3-11e8-8b5a-1db5bcb3e077.png)

**Comment by BenDarby** [comment]
fixed

**Comment by allthatilk** [comment]
@BenDarby can we get a link to the fix so we know what we need to change?

**Comment by BenDarby** [comment]
Hi @allthatilk

The fix was one with just CSS, anything that requires new markup I've been creating as a separate issue with the label markup change. The template is here though http://iati.surge.sh/page-templates/01-5-history

**Comment by akmiller01** [comment]
@BenDarby 

Updated screen.css and the problem at the top persists, unfortunately. It seems to get worse with longer text and more items.

Actual use-case:
![image](https://user-images.githubusercontent.com/2836840/39580975-83222832-4eb8-11e8-9721-5ba17ef5984c.png)

Test use-case:
![image](https://user-images.githubusercontent.com/2836840/39581014-98e88da0-4eb8-11e8-83d1-64771b0b7d9b.png)

**Comment by BenDarby** [comment]
@akmiller01 ah sorry about that, I've just pushed a fix to the css. Try again now and it should hopefully be ok.

**Comment by akmiller01** [comment]
Hey @BenDarby is this the intended appearance now?

![image](https://user-images.githubusercontent.com/2836840/39583760-d2d9e3d2-4ebe-11e8-9088-a7a094d2884f.png)

This is similar to the solution we came up with locally (just setting `top: 0%`).

**Comment by BenDarby** [comment]
@akmiller01 yup that's the one :)
