### ISSUE TITLE
About subpage IE

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Pattern-Library#25]
The hero logo on the about subpage looks different on IE to on other browsers 

![aboutsubie](https://user-images.githubusercontent.com/36768381/39059004-5094a79e-44b5-11e8-87cb-f6b7e5db2262.JPG)

This probably connects to issue 20, they might be the same bug?

**Comment by BenDarby** [comment]
Using a png instead of svg for background image in hero
