### ISSUE TITLE
Table displays horizontal scroll bar at full screen width

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#32]
http://iati.surge.sh/page-templates/06-standard-page

- Chrome, macOS
- Firefox, macOS
- Safari, macOS

<img width="777" alt="screen shot 2018-05-04 at 10 22 38" src="https://user-images.githubusercontent.com/560463/39621064-4d989e26-4f85-11e8-8cd1-1d1b2bdaec5c.png">

**Comment by BenDarby** [comment]
Scrollbar only appears on smaller devices now
