### ISSUE TITLE
Title box on People Page overlaps with the organisation logo

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Pattern-Library#33]
![screen shot 2018-05-04 at 10 41 28](https://user-images.githubusercontent.com/23729009/39621762-bfa91fca-4f87-11e8-9723-9638b0b8e670.png)

![screen shot 2018-05-04 at 10 39 39](https://user-images.githubusercontent.com/23729009/39621724-a22744f4-4f87-11e8-8d2e-e0ae96b095ad.png)

This seems to happen when using over 59 characters.

**Comment by BenDarby** [comment]
added `max-width: 80%;` to listing__metadata class to stop this from happening
