### ISSUE TITLE
Footer layout broken

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#34]
http://iati.surge.sh/page-templates/01-1b-about-subpage-3-levels

- Edge, Windows 10

<img width="1408" alt="screen shot 2018-05-04 at 10 48 19" src="https://user-images.githubusercontent.com/560463/39622059-c5781144-4f88-11e8-9fb7-ee49bb509b26.png">

**Comment by BenDarby** [comment]
Fixed with the same `@supports (display: -ms-grid)` trick
