### ISSUE TITLE
Page displays last list item only

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#35]
http://iati.surge.sh/page-templates/02-2-guidance-section
http://iati.surge.sh/page-templates/02-3-guidance-single
http://iati.surge.sh/page-templates/02-4-guidance-group

- Edge, Windows 10, wide screen width

<img width="1302" alt="screen shot 2018-05-04 at 10 51 26" src="https://user-images.githubusercontent.com/560463/39622234-4c026430-4f89-11e8-8ddc-f0089b0a9100.png">

<img width="1170" alt="screen shot 2018-05-04 at 10 54 08" src="https://user-images.githubusercontent.com/560463/39622296-89cbd486-4f89-11e8-92aa-c46b6b763b25.png">

<img width="1118" alt="screen shot 2018-05-04 at 10 56 25" src="https://user-images.githubusercontent.com/560463/39622366-dae2b452-4f89-11e8-8e24-954288c2cf69.png">

**Comment by BenDarby** [comment]
fixed by adding `@supports (display: -ms-grid;` and disabling css grid as it uses the old implementation which doesn't support auto placement
