### ISSUE TITLE
Contact form layout broken

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#36]
http://iati.surge.sh/page-templates/02-3-guidance-single

- Edge, Windows 10, full screen width

<img width="1252" alt="screen shot 2018-05-04 at 10 54 46" src="https://user-images.githubusercontent.com/560463/39622323-a41a2d42-4f89-11e8-8b12-cc7643de4d8c.png">

**Comment by BenDarby** [comment]
Fixed with the `@supports (display: -ms-grid)` trick to disable css grid
