### ISSUE TITLE
Extra column on table

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#37]
http://iati.surge.sh/page-templates/06-standard-page

- Edge, Windows 10
- IE11, Windows 7

<img width="843" alt="screen shot 2018-05-04 at 10 58 48" src="https://user-images.githubusercontent.com/560463/39622456-307c5bc0-4f8a-11e8-8bc5-47b3e0daebe0.png">

**Comment by BenDarby** [comment]
This seems to be fixed now, may of been a hangover from the horizontal scroll bug
