### ISSUE TITLE
Image and text modules misaligned

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#38]
http://iati.surge.sh/page-templates/02a-guidance-support

- IE11, Windows 7 large screen width
- Safari iPad Mini, iOS 7.0.3, landscape
- Safari iPad Air, iOS 8.3, landscape

<img width="999" alt="screen shot 2018-05-04 at 11 03 54" src="https://user-images.githubusercontent.com/560463/39622653-f5a940d4-4f8a-11e8-8599-f56e15326da6.png">

**Comment by BenDarby** [comment]
fixed my bad maths
