### ISSUE TITLE
Search button style 

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#39]
http://iati.surge.sh/page-templates/02-5-knowledgebase

- Safari iPhone 6, iOS 11.2.5

![img_81b0f42c026d-1](https://user-images.githubusercontent.com/560463/39623705-64c02c14-4f8e-11e8-9d06-2c64c5d84471.jpeg)

**Comment by BenDarby** [comment]
added `-webkit-appearance: none;` on button class to prevent this.
