### ISSUE TITLE
Next step module misaligned

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#40]
http://iati.surge.sh/page-templates/02-3-guidance-single

- Safari iPad Mini, iOS 7.0.3, landscape
- Safari iPad Air, iOS 8.3, landscape

Apologies for poor picture quality!

![img_3120](https://user-images.githubusercontent.com/560463/39627029-32f5cfbe-4f9c-11e8-8c5c-84ed3cdba889.JPG)

**Comment by BenDarby** [comment]
added min-height for browsers not supporting grid
