### ISSUE TITLE
About page hero image extends outside the banner boundaries

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Pattern-Library#41]
This seems to be an issue specific to Chrome v. 66.0.3359.139 as I wasn't getting it before I updated my browser today. But the hero image is overlapping main page content. This seems to get worse as the width of the window decreases.

Wide window
![screen shot 2018-05-04 at 14 50 55](https://user-images.githubusercontent.com/23729009/39632787-f007d4b0-4fad-11e8-80a7-309018d720c9.png)

Narrow window
![screen shot 2018-05-04 at 14 50 17](https://user-images.githubusercontent.com/23729009/39632799-fa5a3c82-4fad-11e8-9dde-3c991dcc9d90.png)

**Comment by BenDarby** [comment]
I've added `overflow: hidden;` to the hero element to prevent this from happening
