### ISSUE TITLE
Bullet points

### ISSUE THREAD

**Issue by jahnvidave** [IATI/IATI-Pattern-Library#46]
Hello,

In the content on some pages we have a second indent of bullet points, but the bullets look the same as the first ones. 
In Wagtail they look different, but this doesn't reflect on the alpha. 

Looking at the page 'How to manage your IATI Registry accounts', compare Wagtail:
![image](https://user-images.githubusercontent.com/38503709/40239888-3a91d56a-5aaf-11e8-9bfb-91e899eb83a2.png)

To how it appears on the alpha:
![image](https://user-images.githubusercontent.com/38503709/40239991-70752d8a-5aaf-11e8-9c13-920f5e85ec29.png)

Also, after a secondary indented bullet point there is an extra line break that is leaving a gap in some lists. 
See page: 'How is an 'activity' defined?'

![image](https://user-images.githubusercontent.com/38503709/40239747-d9bf8c78-5aae-11e8-8f99-5f8f63c58abc.png)

Thanks,
Jahnvi

**Comment by jahnvidave** [comment]
Hello,

There is a related issue, that it is not possible to indent paragraphs. There is some content where we have new paragraphs that follow a bullet point, that should be indented to follow on from the bullet, but there is no style function to indent the paragraphs.

For example, looking at the page 'Using the IATI Datastore' (http://staging2.iatistandard.org/en/using-data/IATI-tools-and-resources/IATI-datastore/):

![image](https://user-images.githubusercontent.com/38503709/42086566-6523ea1e-7b8b-11e8-83f1-733463c78acb.png)

The highlighted paragraphs should be indented in line with the above bullet point (regarding CSVs).

Thanks,
Jahnvi

**Comment by akmiller01** [comment]
![image](https://user-images.githubusercontent.com/2836840/42108677-39b504bc-7ba9-11e8-953e-cb68a1f1b575.png)
