### ISSUE TITLE
Breadcrumb separator isn't displaying

### ISSUE THREAD

**Issue by BenDarby** [IATI/IATI-Pattern-Library#51]
The breadcrumb can't find or load the little separator arrow image, you can see it here on the pattern library http://iati.surge.sh/page-templates/02-4-guidance-group 

I guess it needs adding to assets folder on staging.

**Comment by akmiller01** [comment]
Yep, we've got a missing file. I can add that relatively quickly.

**Comment by akmiller01** [comment]
https://github.com/IATI/preview-website/pull/151 @allthatilk @dalepotter
