### ISSUE TITLE
Home page title goes beyond width on small screens

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#6]
The `<h1>` goes beyond the screen width, and causes horizontal scrolling.

iPhone X:
![img_766b886052b8-1](https://user-images.githubusercontent.com/560463/38310911-a8daec3a-3815-11e8-878c-4257cda703a7.jpeg)

iPhone 5S:
![img_0660689bd16d-1](https://user-images.githubusercontent.com/560463/38311155-60fcb514-3816-11e8-82dd-fbf17ffcda45.jpeg)

![img_230ef4b43c1c-1](https://user-images.githubusercontent.com/560463/38315435-681f53ba-3820-11e8-9c10-01e3b1553fc1.jpeg)

**Comment by BenDarby** [comment]
fixed by added word wrap and hyphens
