### ISSUE TITLE
News articles fallback image and css

### ISSUE THREAD

**Issue by BenDarby** [IATI/IATI-Pattern-Library#61]
Can we use the same fallback image from case studies here as well, the IATI logo as a fallback image doesn't work really. Also there's seems a css style of `min-height: 300px` on the `.listing__aside` element when nested within `.listing--featured` can we remove this please as it breaks the design, it's not present in the pattern library. 
http://staging2.iatistandard.org/en/news/

**Comment by akmiller01** [comment]
Resolved with https://github.com/IATI/IATI-Pattern-Library/pull/47
