### ISSUE TITLE
No bottom margin on final info panel on contact page

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#7]
On small screens, there is no bottom margin on final info panel on the contact page, causing the panel to butt up against the footer.

iPhone X:
![img_793ec1eec015-1](https://user-images.githubusercontent.com/560463/38311445-19865298-3817-11e8-9852-6bec09b1ec1e.jpeg)

**Comment by BenDarby** [comment]
fixed by adding margin bottom on the last element as well
