### ISSUE TITLE
Words break half-way through in header 

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Pattern-Library#72]
![screen shot 2018-07-05 at 12 34 00](https://user-images.githubusercontent.com/23729009/42321129-bddc4c5a-804f-11e8-8e99-1c0ba072001d.png)
 Words shouldn't break in the header. Ideally we want this:
![image](https://user-images.githubusercontent.com/23729009/42321199-04a29cde-8050-11e8-9f6c-7f1741d2c162.png)

**Comment by dalepotter** [comment]
Seems to be a CSS change that is needed:

![image](https://user-images.githubusercontent.com/8247168/42321469-f91cc74e-8050-11e8-85b0-df1b565fd310.png)

**Comment by k8hughes** [comment]
Hi @benjamincoleman would it be possible to look at this one asap?  It's a high priority for us.

**Comment by allthatilk** [comment]
Fixed
