### ISSUE TITLE
Exclude `converted-html` folder from source control?

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Pattern-Library#76]
Currently the pattern library is compiled to HTML by Skelly and stored in `converted-html`. Additionally, the automated deployment process with [Travis compiles the HTML](https://github.com/IATI/IATI-Pattern-Library/blob/master/.travis.yml#L6) as part of it's build process and later [deploys the site to github pages](https://github.com/IATI/IATI-Pattern-Library/blob/master/.travis.yml#L7-L16).

Therefore, is it even helpful to have the compiled HTML under source control? 

I would recommend adding `converted-html` to `.gitignore`.

Any thoughts @BenDarby @urlsangel @benjamincoleman @allthatilk @akmiller01 ??

**Comment by akmiller01** [comment]
Sounds perfectly logical to me!

**Comment by urlsangel** [comment]
As long as `converted-html` ends up in the deployed site then that's all fine.

**Comment by allthatilk** [comment]
Done
