### ISSUE TITLE
Long stats reach outer container edge 

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Pattern-Library#8]
Home page stats:
http://iati.surge.sh/page-templates/0-home

iPhone 5S:
![img_857bf9130132-1](https://user-images.githubusercontent.com/560463/38314605-861303c8-381e-11e8-85ad-57818e76d2b9.jpeg)

**Comment by BenDarby** [comment]
fixed by adding to class `word-wrap: break-word;`
