### ISSUE TITLE
People page - logo text alternative

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#86]
e.g. https://iatistandard.org/en/about/governance/who-runs-iati/

We want to be able to have a text alternative to the logo for these people, due to some organisations having logos whose proportions don't fit the design well. For example: http://www.ba.undp.org/content/bosnia_and_herzegovina/en/home/test_area/undp-logos-and-branding-guidelines.html

Can we have:

1. with logo
2. with text alternative of logo - e.g. "United Nations"
3. neither logo nor text - show nothing to demonstrate this alternative to dev team

**Comment by BenDarby** [comment]
I've updated this template to show the 3 variations http://iati.surge.sh/page-templates/01-4-people

there is some small markup changes for this to work: 
just a logo:
```
<div class="listing__body-img ">
    <img src="/assets/img/logo.png" alt="alt tag">
    <span>Oxfam</span>
</div>
```

text logo: 
```
<div class="listing__body-img listing__body-img--text">
    <img src="/assets/img/logo.png" alt="alt tag">
    <span>United Nations</span>
</div>
```

and you can just make this element optional, so if no logo or text is uploaded then it wont appear
