### ISSUE TITLE
Typekit 403

### ISSUE THREAD

**Issue by Daviniafffunction** [IATI/IATI-Pattern-Library#88]
benjamincoleman commented on 6 Jul

I'm seeing a 403 for Typekit CSS on live:

```esn8rgw.css:1 Failed to load resource: the server responded with a status of 403 ()```

I think you need to check the domain is listed correctly in your Typekit account.

Here's a similar report and some support that will help:

https://forums.adobe.com/thread/1554778

**Comment by Daviniafffunction** [comment]
Moved from preview site repo: https://github.com/IATI/preview-website/issues/189

**Comment by andylolz** [comment]
I don’t see this error. Did someone fix it, perhaps?

**Comment by BenDarby** [comment]
This looks to have been fixed
