### ISSUE TITLE
Guidance Page: 'Contact Support' missing from a child page

### ISSUE THREAD

**Issue by Daviniafffunction** [IATI/IATI-Pattern-Library#90]
sargentfrancesca commented on 3 Jul

Should 'contact support' appear on all guidance pages? this is the PL equiv https://iatistandard.org/en/guidance/preparing-data/what-data-to-publish/

allthatilk commented 9 days ago
>@IATI/bas Any ideas on this question?

amy-silcock commented 9 days ago
>@allthatilk can you explain further please. The 'contact support' is on the guidance pages....? Barr those which just have cards.

**Comment by andylolz** [comment]
It seems like this ticket can just be closed. It’s not a pattern library issue, and the problem described isn’t present on the website (possibly it was fixed since testing).
