### ISSUE TITLE
JS error on homepage and throughout

### ISSUE THREAD

**Issue by Daviniafffunction** [IATI/IATI-Pattern-Library#92]
sargentfrancesca commented on 3 Jul

```basicScroll JS errors (Uncaught TypeError: Cannot read property 'track' of null)```

![image](https://user-images.githubusercontent.com/40493680/44214634-87187d80-a168-11e8-8503-f8a8bec1cd7e.png)

@BenDarby @benjamincoleman 

allthatilk commented 9 days ago
This one needs a status update as I can't see them on the live site:
![image](https://user-images.githubusercontent.com/40493680/44214721-b5965880-a168-11e8-940f-dd38849c7419.png)

**Comment by andylolz** [comment]
Looks like this javascript is specifically for the floaty featured news on this page:
https://iatistandard.org/en/news/

So if there’s nothing on the page with class `listing__body`, this error appears.
