### ISSUE TITLE
Current active nav item not underlined in menu

### ISSUE THREAD

**Issue by Daviniafffunction** [IATI/IATI-Pattern-Library#93]
sargentfrancesca commented on 3 Jul 

See events nav item on PL: http://iati.surge.sh/page-templates/04-events

This is underlined as the page is active. This does not happen on https://iatistandard.org/en/events/

benjamincoleman commented 8 days ago
Implementation problem on the live site, rather than the pattern lib.

**Comment by andylolz** [comment]
This isn’t a pattern library issue. It’s correct in the pattern library. It’s wrong on the live site.

**Comment by BenDarby** [comment]
Yeah the live site needs the class `navigation-utility__item--active ` adding to the active links in the utility nav

**Comment by andylolz** [comment]
Thanks! I’ve moved your comment across to https://github.com/IATI/preview-website/issues/177.

This issue should be closed.
